# Generated by Django 2.0 on 2018-09-28 02:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionesArchivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArchivo', models.CharField(default='', max_length=50)),
                ('estatus', models.CharField(default='', max_length=10)),
                ('fechaEjecucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ejecucion')),
            ],
        ),
        migrations.CreateModel(
            name='Compania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompaniaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportesVC.Compania')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EjecucionReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=2)),
                ('anoPeriodo', models.CharField(max_length=4)),
                ('diaIniciaPeriodo', models.CharField(max_length=2)),
                ('diaFinPeriodo', models.CharField(max_length=2)),
                ('fechaEjecucion', models.DateTimeField(verbose_name='Fecha de ejecucion')),
                ('estatus', models.CharField(default='', max_length=10)),
                ('nombreArchivo', models.CharField(default='', max_length=50)),
                ('rutaArchivo', models.CharField(default='', max_length=100)),
                ('nombreZip', models.CharField(default='', max_length=50)),
            ],
            options={
                'permissions': (('can_run_Report', 'Ejecuta Reporte'), ('can_run_Calculos', 'Ejecuta Calculos'), ('can_run_Conciliacion', 'Ejecuta Conciliacion'), ('can_run_AdminConta', 'Administracion Conta')),
            },
        ),
        migrations.CreateModel(
            name='MesReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombreLargo', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VariablesUltimoReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('valor', models.CharField(max_length=50)),
                ('editable', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='mesPeriodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportesVC.MesReporte'),
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='tipoReporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportesVC.TipoReporte'),
        ),
        migrations.AddField(
            model_name='ejecucionreporte',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualizacionesarchivos',
            name='tipoReporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportesVC.TipoReporte'),
        ),
        migrations.AddField(
            model_name='actualizacionesarchivos',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
